### 학습목표
- 데이터 분석을 위한 기술통계량 탐색하기
- 실데이터를 활용하여 기술통계량 확인하기

In [22]:
#라이브러리 불러오기
import pandas as pd
#데이터 불러오기
import chardet

with open('./data/hr-info.csv','rb') as f:
    data = f.read()

chardet.detect(data)

#위 내용은 인코딩에 무엇을 써야할지 알아보는 계산식이다

# 밑내용이 폴더를 불러오는 함수다.

hr_info = pd.read_csv('./data/hr-info.csv',encoding = 'EUC-KR',index_col='EID')

hr_info

,ENAME,GENDER,ORG_CD,POS_CD,AGE,SERVICE_YEAR,EDU_LEVEL,PERFORMANCE_SCORE,SALARY,LAST_PROMO_DT,TRAINING_HOURS,SKILLS,ACTIVE_STATE,HIRE_DATE,RETIRE_DATE,RETIRE_REASON,REHIRE_YN,NATION,ROUNDING_DEDUCTION
EID,,,,,,,,,,,,,,,,,,,
E00206,시이오,M,NaN,P001,49,25,박사 학위,4.50,10200,2024-03-01,240,"Marketing, Salesforce",Y,1999-03-01,NaN,NaN,NaN,KOREA,Y
E00181,나사장,F,NaN,P002,49,24,박사 학위,4.60,9500,2024-03-01,236,"Project Management, Marketing",Y,2000-03-01,NaN,NaN,NaN,KOREA,Y
E00164,난부사장,M,NaN,P003,48,22,박사 학위,4.60,9100,2024-03-01,240,"Salesforce, Data Analysis, Java",Y,2002-03-01,NaN,NaN,NaN,KOREA,Y
E00190,판라다,F,ORG007,P004,47,18,박사 학위,3.51,8500,2024-03-01,96,"Java, Data Analysis, Salesforce",Y,2006-03-01,NaN,NaN,NaN,KOREA,Y
E00209,누훈봉,M,ORG023,P004,47,19,박사 학위,3.38,8600,2023-03-01,66,"Java, Salesforce",Y,2005-03-01,NaN,NaN,NaN,KOREA,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
E00322,부탐회,F,ORG014,P009,23,0,학사 학위,0.00,4500,NaN,4,Java,Y,2024-09-01,NaN,NaN,NaN,KOREA,N
E00389,초두반,F,ORG012,P009,23,0,학사 학위,0.00,4500,NaN,4,"Salesforce, Java",Y,2024-09-01,NaN,NaN,NaN,KOREA,N
E00438,권개득,M,ORG024,P009,23,0,학사 학위,0.00,4500,NaN,4,Python,Y,2024-09-01,NaN,NaN,NaN,KOREA,N
E00304,탐출조,M,ORG009,P009,24,0,학사 학위,0.00,4500,NaN,4,Salesforce,Y,2024-09-01,NaN,NaN,NaN,KOREA,N
E00428,을충나,F,ORG003,P009,24,0,학사 학위,0.00,4500,NaN,4,"Data Analysis, Python, Marketing",Y,2024-09-01,NaN,NaN,NaN,KOREA,N

In [23]:
# 데이터 정보 확인 hr_info.info()


hr_info.info()

<class 'pandas.core.frame.DataFrame'>
Index: 200 entries, E00206 to E00428
Data columns (total 19 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   ENAME               200 non-null    object
 1   GENDER              200 non-null    object
 2   ORG_CD              197 non-null    object
 3   POS_CD              200 non-null    object
 4   AGE                 200 non-null    int64
 5   SERVICE_YEAR        200 non-null    int64
 6   EDU_LEVEL           200 non-null    object
 7   PERFORMANCE_SCORE   200 non-null    float64
 8   SALARY              200 non-null    int64
 9   LAST_PROMO_DT       182 non-null    object
 10  TRAINING_HOURS      200 non-null    int64
 11  SKILLS              200 non-null    object
 12  ACTIVE_STATE        200 non-null    object
 13  HIRE_DATE           200 non-null    object
 14  RETIRE_DATE         49 non-null     object
 15  RETIRE_REASON       49 non-null     object
 16  REHIRE_YN           49 non-null     object
 17  NATION              200 non-null    object
 18  ROUNDING_DEDUCTION  200 non-null    object
dtypes: float64(1), int64(4), object(14)
memory usage: 31.2+ KB

In [20]:
# 기술통계확인하기
# 기본적으로 숫자 데이터에 대한 기술통계를 반환
hr_info.describe()

,AGE,SERVICE_YEAR,PERFORMANCE_SCORE,SALARY,TRAINING_HOURS
count,200.000000,200.000000,200.000000,200.000000,200.000000
mean,31.930000,4.660000,1.919900,5987.000000,34.745000
std,7.111114,6.183492,1.748062,1182.676889,40.470971
min,22.000000,0.000000,0.000000,4500.000000,0.000000
25%,27.000000,0.000000,0.000000,5000.000000,4.000000
50%,30.000000,1.000000,1.795000,5600.000000,21.000000
75%,37.000000,8.000000,3.412500,6825.000000,56.750000
max,49.000000,25.000000,4.960000,10200.000000,240.000000

## 기술통계 확인하기(요약, 수치)
- 기술 통계 확인하는 이유
  - 데이터 분석에서 가장 중요한 첫 단계는 데이터를 이해하는 것
  - 데이터 범위·대표값·이상치 파악
  - 데이터 비율·경향·불균형 파악
  -> 결측치가 생기면 단순 삭제하는것이 아니라 기술통계량을 확인하여 대체할만한 값들을 탐색하여 결측치 처리

### data.describe()
- 숫자형 데이터의 전체적인 ‘요약 정보’를 빠르게 파악할 수 있음

- 반환되는 정보

  - count : 데이터 개수
  - mean : 평균
  - std : 표준편차 -> 데이터의 분포 파악 -> 분산에 루트를 씌운 값, 데이터가 얼마나 흩어져 있는가
  - min, max : 최소값, 최댓값
  - 25%, 50%(중위수, 중앙값), 75% : 사분위수(데이터의 분포를 4등분 확인)

### data.describe(include = 'object')

- 문자형(object, 범주형) 데이터만 선택해 기술통계를 보여줌

- 반환되는 정보

 - count : 데이터 개수

 - unique : 고유값 개수

 - top : 가장 많이 등장한 값

 - freq : top 값의 등장 빈도

In [26]:
hr_info.describe()

,AGE,SERVICE_YEAR,PERFORMANCE_SCORE,SALARY,TRAINING_HOURS
count,200.000000,200.000000,200.000000,200.000000,200.000000
mean,31.930000,4.660000,1.919900,5987.000000,34.745000
std,7.111114,6.183492,1.748062,1182.676889,40.470971
min,22.000000,0.000000,0.000000,4500.000000,0.000000
25%,27.000000,0.000000,0.000000,5000.000000,4.000000
50%,30.000000,1.000000,1.795000,5600.000000,21.000000
75%,37.000000,8.000000,3.412500,6825.000000,56.750000
max,49.000000,25.000000,4.960000,10200.000000,240.000000

In [28]:
hr_info.describe(include = 'object')

,ENAME,GENDER,ORG_CD,POS_CD,EDU_LEVEL,LAST_PROMO_DT,SKILLS,ACTIVE_STATE,HIRE_DATE,RETIRE_DATE,RETIRE_REASON,REHIRE_YN,NATION,ROUNDING_DEDUCTION
count,200,200,197,200,200,182,200,200,200,49,49,49,200,200
unique,200,2,30,9,5,4,91,2,16,8,6,2,6,2
top,시이오,M,ORG021,P008,학사 학위,2024-03-01,Salesforce,Y,2024-03-01,2024-03-01,이직,N,KOREA,Y
freq,1,117,12,55,159,111,24,151,64,19,28,45,102,150

In [ ]:
###: 통계값, 개별확인
    -총합,평균,개수, 중복값

In [28]:
# 연간 인건비
int(hr_info['SALARY'].sum())

1197400

In [32]:
#평균 연봉
float(hr_info['SALARY'].mean())

5987.0

- 데이터의수 : count(), value_counts()

In [34]:
#count() 데이터의 수->
#퇴사자의 수
int(hr_info['RETIRE_DATE'].count())  #->결측지 값을 세지않는다...!

49

In [35]:
# value_counts() : 컬럼에 있는 고유값 개수(unique)한 값들을 기준으로 개수를 세주는 함수

hr_info['GENDER'].value_counts()

GENDER
M    117
F     83
Name: count, dtype: int64

In [42]:
#전체 직원의 남자 비율 확인
men_cnt = hr_info['GENDER'].value_counts()['M']

total_cnt = hr_info['ENAME'].count()


float(men_cnt / total_cnt *100)

58.5

- unique()

In [44]:
# 중복되지 않은 유일한 값들을 추출
# 직원들의 국적 종류 확인
hr_info['NATION'].unique()

array(['KOREA', 'Japan', 'USA', 'India', 'China', 'UK'], dtype=object)

In [45]:
#국적에 따른 인원수
hr_info['NATION'].value_counts()

NATION
KOREA    102
USA       22
India     22
Japan     21
UK        18
China     15
Name: count, dtype: int64

- median()

In [49]:
hr_info['AGE'].median()

30.0

In [ ]:
#실습
#교육수준('EDU_LEVEL')에 따른 평균 연봉

In [5]:
edu_uni = hr_info['EDU_LEVEL'].unique()

edu_uni

array(['박사 학위', '학사 학위', '석사 학위', '고등학교 졸업', '전문대 학위'], dtype=object)

In [16]:
#박사 학위의 평균 연봉 구하기
#1. 박사학위 데려오기

a = hr_info[hr_info['EDU_LEVEL'] == '박사 학위'][['SALARY']]
A = hr_info[hr_info['EDU_LEVEL'] == '학사 학위'][['SALARY']]
b = hr_info[hr_info['EDU_LEVEL'] == '석사 학위'][['SALARY']]
c = hr_info[hr_info['EDU_LEVEL'] == '고등학교 졸업'][['SALARY']]
d = hr_info[hr_info['EDU_LEVEL'] == '전문대 학위'][['SALARY']]

print(a['SALARY'].mean().round(2))
print(A['SALARY'].mean().round(2))
print(b['SALARY'].mean())
print(c['SALARY'].mean())
print(d['SALARY'].mean())

8166.67
5727.04
6900.0
6140.0
5050.0

In [14]:
print(hr_info[hr_info['EDU_LEVEL'] == '박사 학위']['SALARY'].mean().round(2))

8166.67

In [20]:
a = hr_info[hr_info['EDU_LEVEL'] == '박사 학위']['SALARY']
print(a.mean().round(2))

8166.67

In [29]:
for i in edu_uni:
    result = hr_info[hr_info['EDU_LEVEL'] == i]['SALARY'].mean().round(2)
    print(f"{i}: {result}")

#Pandas에서 group by는 위와같은 for i 함수를 도와주는 도구다.

박사 학위: 8166.67
학사 학위: 5727.04
석사 학위: 6900.0
고등학교 졸업: 6140.0
전문대 학위: 5050.0

- 데이터 그룹화를 이용한 통계분석
  - groupby(): 카테고리별 그룹을 만들어 연산 수행

In [37]:
# 교육 수준에 따른 평균 연봉 구하기
# 데이터.groupby(기존 컬럼명).연산함수
# EDU_LEVEL, SALARY
hr_info[['EDU_LEVEL', 'SALARY']].groupby('EDU_LEVEL').mean().round(2)

# 카테고리로 설정할 데이터가 들어있는 컬럼을 기준컬럼이라고 한다!

            SALARY
EDU_LEVEL
고등학교 졸업    6140.00
박사 학위      8166.67
석사 학위      6900.00
전문대 학위     5050.00
학사 학위      5727.04

In [34]:
hr_info.columns

Index(['ENAME', 'GENDER', 'ORG_CD', 'POS_CD', 'AGE', 'SERVICE_YEAR',
       'EDU_LEVEL', 'PERFORMANCE_SCORE', 'SALARY', 'LAST_PROMO_DT',
       'TRAINING_HOURS', 'SKILLS', 'ACTIVE_STATE', 'HIRE_DATE', 'RETIRE_DATE',
       'RETIRE_REASON', 'REHIRE_YN', 'NATION', 'ROUNDING_DEDUCTION'],
      dtype='object')

In [40]:
# 교육수준과 성별로 나눠서 평균연봉 확인하기

hr_info[['EDU_LEVEL','SALARY','GENDER']].groupby(['EDU_LEVEL','GENDER']).mean().round(2)

                   SALARY
EDU_LEVEL GENDER
고등학교 졸업   F       6200.00
          M       6100.00
박사 학위     F       8425.00
          M       8037.50
석사 학위     F       7233.33
          M       6525.00
전문대 학위    F       5600.00
          M       4500.00
학사 학위     F       5643.08
          M       5785.11

In [41]:
# 성별에 따른 평균연봉 구하기

hr_info[['GENDER','SALARY']].groupby('GENDER').mean().round(2)

         SALARY
GENDER
F       5975.90
M       5994.87

- aggregate(집계하다, 요약하다)
- agg : 요약 통계를 한 번에 여러 개 뽑고 싶을 때 사용, 즉 agg()는 그룹별로 묶은 데이터를
어떤 방식으로 요약할지 지정하는 함수

In [47]:
hr_info[['GENDER','SALARY']].groupby('GENDER').agg(['mean','max','min','median']).round(2) #agg는 그룹바이함수에서만 사용한다.

         SALARY
           mean    max   min  median
GENDER
F       5975.90   9500  4500  5600.0
M       5994.87  10200  4500  5600.0